title: Chinh Mai # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  👋 Hi, I’m Chinh Mai 
  <br><br>
  a passionate self-taught data analyst. Holding a B.Sc in Finance and Accounting and a M.Sc in International Management with a focus on Marketing, I'm learning myself to become a full-time data analyst. I love to use data analytics to explore my favorite topics and visualize results to tell stories. 
  <br><br>
  <a href="https://www.linkedin.com/in/chinhxuan/">View my LinkedIn profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
