title: Chinh Mai # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  👋 Hi, I’m Chinh Mai,
  <br><br>
  Welcome to my portfolio page!
  <br><br>
  With a background in Finance and Marketing, my projects focus on using analytics tool to study my favorite topics in these fields.
  <br><br>
  My projects are all designed with replicability in mind, you can check the project overview to see the executive summary and find the detailed documentation. The workbook of each project is also provided if you're interested in the technical details.
  <br><br>
  Send me messages to discuss the details of my works.
  <br><br>
  <a href="https://www.linkedin.com/in/chinhxuan/">View my LinkedIn profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
