title: Chinh Mai # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  👋 Hi, I’m Chinh Mai,
  <br><br>
  Welcome to my portfolio page!
  <br><br>
  With a background in Finance and Marketing, my projects focus on using analytics tool to study my favorite topics in these fields.
  <br><br>
  <a href="https://www.linkedin.com/in/chinhxuan/">View my LinkedIn profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
